### ISSUE TITLE
Coral-Select with a current value together with a showhide, doesn't show the current selected value on a fresh page

### ISSUE THREAD

**Issue by rubnig** [wcm-io/io.wcm.wcm.ui.granite#4]
A redirect page together with the wcm.io Link Handler doesn't show the initial selected hidden fields on page load.

The Link Tab comes from: https://github.com/wcm-io/io.wcm.handler.link/blob/16fa9481eddaab40c59586910b878b40dbd1051b/src/main/webapp/app-root/components/page/redirect.json#L15

and eventually includes a `<coral-select>` in https://github.com/wcm-io/io.wcm.handler.link/blob/16fa9481eddaab40c59586910b878b40dbd1051b/src/main/webapp/app-root/components/granite/form/linkRefContainer/linkRefContainer.jsp#L250

This `granite/ui/components/coral/foundation/form/select` doesn't seem to support to set the `<input>` field its `value` attribute when loading a page, but sets it as an empty string. Only after interacting with the field the bound input gets the current value set.

The current showhide logic from https://github.com/wcm-io/io.wcm.wcm.ui.granite/blob/develop/src/main/webapp/app-root/clientlibs/io.wcm.ui.granite.showhidedialogfields/js/showhide.js#L72 checks the `component.value` which on payload contains an empty string, but for a `<coral-select>` it is possible to find the currently selected value by looking for a child element of type `<coral-select-item>` with a `selected` attribute.

Therefore I propose to the determine the selected value for coral-select in a different way, so the show-hide mechanism will work as expected:

```javascript
else if ($(element).is("coral-select")) {
    value = $(element).children('coral-select-item[selected]').val() || "";
}
```

Following content wouldn't be visible at page load for a redirect page:
![image](https://github.com/wcm-io/io.wcm.wcm.ui.granite/assets/8969453/29ab678c-d6d4-4937-a2a8-d9b081b7c09f)

for the following page properties:
![image](https://github.com/wcm-io/io.wcm.wcm.ui.granite/assets/8969453/d76fd36f-3cce-4377-b822-01a0b0b90c29)

**Comment by rubnig** [comment]
Proposed fix: https://github.com/wcm-io/io.wcm.wcm.ui.granite/pull/5

**Comment by stefanseifert** [comment]
can you describe the usecase in more detail when you observe the problem you want to fix?

is it in the "create page" dialog when a new redirect page is created?
or is it when the page properties dialog of an already created redirect page is opened?

in the former case (new page dialog), i observe that the whole clientlib io.wcm.ui.granite.showhidedialogfields is not loaded at all, thus the show/hide feature does not work at all (that's why we usually hide the link tab in the create page dialog e.g. see [here](https://github.com/wcm-io/io.wcm.samples/blob/0288c44064155fac90a15ff1b5be18d503007c21/bundles/core/src/main/webapp/app-root/components/global/include/linkRefNoTitleTab.json#L6)).

in the latter case it works fine for me with the original code.

**Comment by stefanseifert** [comment]
thanks for the detailed steps!
i was able to reproduce the problem with AEM 6.5.17 and AEM 6.5.18, also with our sample app https://github.com/wcm-io/io.wcm.samples - the problem does not occur in latest AEMaaCS SDK. but your fix also does not harm there, so i'm fine with applying it.
